export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

zstyle ':omz:update' mode auto

plugins=(
  git
  docker
  docker-compose
  gradle
  mvn
  spring
  history
  colored-man-pages
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export SPRING_PROFILES_ACTIVE=local
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
export PATH=$JAVA_HOME/bin:$PATH
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

alias ll='ls -la'
alias gs='git status'
alias gc='git commit'
alias gp='git pull'
alias gps='git push'
alias gco='git checkout'
alias gbr='git branch'
alias gl='git log --oneline --graph --decorate'
alias dc='docker-compose'
alias k='kubectl'
alias gr='./gradlew'
alias grb='./gradlew build'
alias grt='./gradlew test'
alias grr='./gradlew bootRun'

alias run-app='./gradlew bootRun -Dspring.profiles.active=local'
alias build-app='./gradlew clean build'
alias test-app='./gradlew test'

HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select
